#! /bin/bash
cp .bash_profile ~/.bash_profile; cp .vimrc ~/.vimrc ; cp .zshrc ~/.zshrc ; cp .plan ~/.plan ; source ~/.bash_profile
if grep -q .bash_profile ~/.bashrc; then 
    exit 
else 
cat <<EOT >> ~/.bashrc
if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi
EOT
fi
