#! /bin/bash

# Installs taps and brews for HomeBrew listed in textfile.

tapsfile="installedTaps.txt"
brewfile="installedBrews.txt"

while read -r line
do  
    brew tap $line
done < "$tapsfile"

brew update

while read -r line
do
    brew install $line
done < "$brewfile"
