#! /bin/bash

# Installs macports listed in textfile.

filename="installedPorts.txt"

if (( $UID != 0 )); then
    echo "Not root, exiting.."
    exit 1
fi

sudo port selfupdate
sudo port upgrade outdated

while read -r line
do
    sudo port install $line > /dev/null 2>&1
    echo $line 
done < "$filename"
