#! /bin/bash

# Installs macports listed in textfile.

filename="installedPorts.txt"

sudo port selfupdate
sudo port upgrade outdated

while read -r line
do
    sudo port install $line > /dev/null 2>&1
    echo $line 
done < "$filename"
