#! /bin/bash

if [[ "$(uname)" == "Darwin" ]]; then 
    cp settings.json ~/Library/Application\ Support/Code/User/settings.json
elif [[ "$(uname)" == "Linux" ]]; then
    cp settings.json ~/.config/Code/User/settings.json
fi 
